### ISSUE TITLE
Unrecognised volume spec: invalid volume specification: 'c:minecraftconfig'

### ISSUE THREAD

**Issue by brikeyes** [nicholasdille/docker#1]
Hi , I went to build this I get this error 

Unrecognised volume spec: invalid volume specification: 'c:minecraftconfig' 

I am guessing it should be c:/minecraft/config  and somehow got messed up

thanks 

C:\minecraft\docker-master (2)\docker-master\minecraft> .\docker-build.cmd

C:\minecraft\docker-master (2)\docker-master\minecraft>docker build -t nicholasdille/minecraft .
Sending build context to Docker daemon  5.12 kB
Step 1/9 : FROM nicholasdille/javaruntime:nano
 ---> da2e38cd7bbf
Step 2/9 : MAINTAINER nicholas.dille@mailbox.org
 ---> Using cache
 ---> 58b770069dc7
Step 3/9 : SHELL powershell -Command
 ---> Using cache
 ---> 5bcafa07aa64
Step 4/9 : ENV JAVA_MEM_START 32m JAVA_MEM_MAX 1024m
 ---> Using cache
 ---> d2c3262551c6
Step 5/9 : RUN mkdir c:\minecraft,c:\minecraft\config,c:\minecraft\plugins,c:\minecraft\worlds
 ---> Using cache
 ---> b0c6e4909585
Step 6/9 : ADD entry.ps1 /
 ---> Using cache
 ---> 3cf5e9e8a477
Step 7/9 : ENTRYPOINT c:\entry.ps1
 ---> Using cache
 ---> e1b6586282f1
Step 8/9 : EXPOSE 25565 25575
 ---> Using cache
 ---> e77129af2a97
Step 9/9 : VOLUME c:\minecraft\config c:\minecraft\plugins c:\minecraft\worlds
Unrecognised volume spec: invalid volume specification: 'c:minecraftconfig'

**Comment by brikeyes** [comment]
I change the backslash to a forward slash and it seems to build ok now 

VOLUME c:/minecraft/config c:/minecraft/plugins c:/minecraft/worlds

**Comment by brikeyes** [comment]
now I get "Error: Unable to access jarfile C:\minecraft\plugins" 

but I am assuming that I will have to supply a jar file for it , I am looking into that now

**Comment by nicholasdille** [comment]
I'll look into the errors ASAP! 

Concerning the jar file.. You need to create your own image and add a jar. I'll update the Readme to clarify! 

See my blog at Dille.name for a guide to compile spigotmc :-)

**Comment by brikeyes** [comment]
thanks so much , I am very new to this Docker on Windows stuff . I really appreciate the work you have done with this ! 

    On Friday, January 6, 2017 1:53 AM, Nicholas Dille <notifications@github.com> wrote:
 

 I'll look into the errors ASAP!Concerning the jar file.. You need to create your own image and add a jar. I'll update the Readme to clarify!See my blog at Dille.name for a guide to compile spigotmc :-)—

**Comment by nicholasdille** [comment]
@brikeyes The `Dockerfile` works great for me... even with the VOLUME statement including backslashes. Can you send me the output of your `docker info`?

**Comment by brikeyes** [comment]
C:\minecraft>docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 21
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: active
 NodeID: 9s87fksany9vsmq3ooup3vtuo
 Is Manager: false
 Node Address: 192.168.56.57
Default Isolation: process
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 6 GiB
Name: docker-windows16-1
ID: V534:RXV7:44SK:FMK2:2DHW:2DZG:6ZR5:Y4HF:I7ST:GPF5:4EKT:7TXG
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: brikeyes
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

C:\minecraft>

**Comment by brikeyes** [comment]
I am confused , what dockerfile would I run to create this ? Is there more than one dockerfile that I need ?
if so in what order do I have to run them?

thanks again for all the help!

**Comment by nicholasdille** [comment]
@brikeyes First of all, I think your build error is related to the docker version you are running (1.12.2-cs2-ws-beta). I am testing on 1.13.0-dev. But using slashes for the VOLUME statement is supported and makes sense as a workaround.

Concerning you latest question...  Unfortunately, I cannot give you a comprehensive introduction to docker and containers here but hopefully the following will make the layering clearer:

```
Your Minecraft server image    --> minecraft (based on Dockerfile.example)
Generic Minecraft server image --> nicholasdille/minecraft
Java image                     --> nicholasdille/javaruntime
Base image                     --> microsoft/windowsservercore
```

Imagine the contents of the container to be the merged contents of those layered images where higher images overwrite the contents of lower images.

**Comment by nicholasdille** [comment]
Workaround: Use slashes in VOLUME statement

**Comment by srija98** [comment]
m

**Comment by srija98** [comment]
How Unrecognised volume spec: invalid volume specification: '/opt/robotframework
problem in dockerfile
