### ISSUE TITLE
do I need to download a client to connect  to this mindcraft

### ISSUE THREAD

**Issue by brikeyes** [nicholasdille/docker#2]
it seem like i have this running now as a container on windows , but how to connect to it? I cannot seem to browse to the IP , do I need a client , if so what exactly ?

thanks

**Comment by nicholasdille** [comment]
[Minecraft](https://g.co/kgs/pPnXD5) is a game which is now owned by Microsoft. To connect to the Microsoft nearest server you need the client which is available for various platforms.

Before you can connect with the client you also need to expose the container ports on the host. See the -p switch for docker run.
